version: "3.7"
services:
  db:
    image: postgres
    container_name: lp_db
    environment:
      POSTGRES_DB: lazypants
      POSTGRES_USER: lazypants
      POSTGRES_NAME: lazypants
      POSTGRES_PASSWORD: lazypants
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - default
    ports:
      - "8125:8125"
volumes:
  data:
